name: HeartUnderName
main: me.yvant.HeartUnderName
version: 1.0
api-version: 1.20
commands:
  healthbar:
    description: Reload the health bar config
    usage: /<command>
    permission: healthbar.reload
permissions:
  healthbar.reload:
    default: op
